name: Graphcore copyright header check
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run test_copyright.py
        run: python3 utils/test_copyright.py
